######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 21 21:52:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += helpdialog.h mainwindow.h ui_helpdialog.h \ ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += notepad.qrc
